# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqQPvhTqo35bDkzTA6f9MGFFLkn5WLJ1

# Classification Model Using Iris Dataset

Objective:
Build a basic classification model using a small dataset. The project demonstrates data loading, data splitting, model training, prediction, and evaluation.
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

"""Importing the required libraries for data handling, model training, and evaluation."""

iris = load_iris()

X = iris.data
y = iris.target

print("Feature Names:")
print(iris.feature_names)

print("\nTarget Names:")
print(iris.target_names)

"""Loading and understanding the Iris dataset. The dataset contains flower measurements and species labels."""

df = pd.DataFrame(X, columns=iris.feature_names)
df["species"] = y

print(df.head())

"""Dataset Exploration

The dataset is explored to understand its structure, dimensions, data types, and statistical properties before training the model.
"""

print("Dataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())

"""Displaying the first five records of the dataset to understand its structure and features."""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

"""Splitting the dataset into training and testing sets. Eighty percent of the data is used for training and twenty percent for testing."""

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

print("Model Training Completed")

"""Training a Decision Tree Classifier using the training dataset."""

y_pred = model.predict(X_test)

print("Predictions:")
print(y_pred)

"""Using the trained model to predict the species of flowers in the testing dataset."""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""Confusion Matrix

The confusion matrix is used to compare actual values with predicted values and evaluate the performance of the classification model.
"""

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""Evaluating the model using accuracy and classification report to measure its performance.

Conclusion:

A basic classification model was successfully built using the Iris dataset. The dataset was loaded and explored, divided into training and testing sets, and a Decision Tree Classifier was trained. The model achieved high accuracy in predicting flower species, demonstrating the fundamentals of supervised machine learning.
"""